# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mee_email@gmail.com
author_name: Rohitha Koppu
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: crimelens-contracts

